# Generated by Django 5.2.1 on 2025-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_address_alter_member_joined_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(default='Not provided'),
        ),
    ]
