# Generated by Django 5.2.1 on 2025-06-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
    ]
