# Generated by Django 5.2.1 on 2025-06-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ad',
            field=models.CharField(default='Not provided', max_length=100),
        ),
    ]
