# Generated by Django 5.2.1 on 2025-06-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='ad',
            new_name='address',
        ),
    ]
