# Generated by Django 5.2.1 on 2025-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_rename_ad_member_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.AddField(
            model_name='member',
            name='no',
            field=models.IntegerField(default=3),
        ),
    ]
