# Generated by Django 5.2.1 on 2025-06-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_member_address_member_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='no',
        ),
    ]
